// Generated by node build-background.mjs. Edit the source modules.
(()=>{
const DOCUMENT_EXTENSIONS = /\.(pdf|pptx?|docx?|xlsx?|txt|csv|od[pts]|rtf)$/i;
const MIME_EXTENSIONS = {
  "application/pdf": "pdf",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/msword": "doc",
  "application/vnd.ms-powerpoint": "ppt",
  "application/vnd.ms-excel": "xls",
  "text/plain": "txt",
  "text/csv": "csv"
};

function isBlackboardURL(value) {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && !url.username && !url.password && (url.hostname === "blackboard.com" || url.hostname.endsWith(".blackboard.com"));
  } catch { return false; }
}

function isAWSAcademyURL(value) {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && !url.username && !url.password && (url.hostname === "awsacademy.instructure.com" || url.hostname === "emergingtalent.contentcontroller.com" || url.hostname === "awsacademy.contentcontroller.com");
  } catch { return false; }
}

function isSupportedPageURL(value) {
  return isBlackboardURL(value) || isAWSAcademyURL(value);
}

function isAllowedDownloadURL(value) {
  if (isSupportedPageURL(value)) return true;
  try {
    const url = new URL(value);
    return url.protocol === "https:" && !url.username && !url.password && (url.hostname.endsWith(".cloudfront.net") || url.hostname.endsWith(".amazonaws.com"));
  } catch { return false; }
}

function decodeFilename(value) {
  try { return decodeURIComponent(value); } catch { return value; }
}

function safeFilename(value, fallback = "Blackboard-document.pdf") {
  const cleaned = String(value || "").normalize("NFC")
    .replace(/[\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069]/g, "")
    .replace(/[<>:"/\\|?*]/g, "_")
    .replace(/\.{2,}/g, "_")
    .replace(/^[.\s]+|[.\s]+$/g, "");
  if (!cleaned) return fallback;
  const guarded = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(cleaned) ? `_${cleaned}` : cleaned;
  if (guarded.length <= 180) return guarded;
  const extension = guarded.match(/\.[a-z0-9]{1,8}$/i)?.[0] || "";
  return guarded.slice(0, 180 - extension.length) + extension;
}

function filenameFromURL(value) {
  const url = new URL(value);
  const disposition = url.searchParams.get("response-content-disposition") || "";
  const utf8 = disposition.match(/filename\*\s*=\s*(?:UTF-8|utf-8)'[^']*'([^;]+)/i);
  const basic = disposition.match(/filename\s*=\s*(?:"([^"]+)"|([^;]+))/i);
  const name = utf8 ? decodeFilename(utf8[1].trim()) : basic ? (basic[1] || basic[2]).trim() : decodeFilename(url.pathname.split("/").pop() || "");
  return name;
}

function candidateFile(source, label, format, fromViewer) {
  if (!isBlackboardURL(source)) return null;
  const url = new URL(source);
  // An inline-only bbcswebdav URL returns viewer HTML, not the original file.
  if (url.pathname.includes("/bbcswebdav/") && (url.searchParams.get("render") === "inlineOnly" || url.searchParams.get("isInlineRender") === "true")) return null;
  const sourceName = filenameFromURL(source);
  const mimeExtension = MIME_EXTENSIONS[(url.searchParams.get("response-content-type") || "").toLowerCase()];
  const labelName = String(label || "").match(/([^\n]+\.(?:pdf|pptx?|docx?|xlsx?|txt|csv|od[pts]|rtf))\s*$/i)?.[1];
  let name = DOCUMENT_EXTENSIONS.test(sourceName) ? sourceName : labelName || "";
  if (name && (format === "pdf" || mimeExtension === "pdf") && !/\.pdf$/i.test(name)) name = name.replace(DOCUMENT_EXTENSIONS, ".pdf");
  if (!name && (format === "pdf" || mimeExtension)) name = `Blackboard-document.${format === "pdf" ? "pdf" : mimeExtension}`;
  if (!name || !DOCUMENT_EXTENSIONS.test(name)) return null;
  if (!fromViewer && !/\.files\.blackboard\.com$/i.test(url.hostname) && !url.pathname.includes("/bbcswebdav/") && !DOCUMENT_EXTENSIONS.test(url.pathname)) return null;
  const filename = safeFilename(name);
  return { url: source, filename, type: filename.split(".").pop().toUpperCase(), variant: format === "pdf" ? "PDF preview file" : "Original document" };
}

function awsPDF(candidate) {
  if (!isAWSAcademyURL(candidate.contextURL || candidate.url) || !isAllowedDownloadURL(candidate.url)) return null;
  const url = new URL(candidate.url);
  const pdf = /\.pdf$/i.test(url.pathname) || url.searchParams.get("response-content-type")?.toLowerCase() === "application/pdf";
  if (!pdf) return null;
  // External AWS storage is accepted only when the supported course frame
  // already loaded it. Citation links alone do not authorize external hosts.
  if (!isAWSAcademyURL(candidate.url) && candidate.kind !== "resource" && candidate.kind !== "captured") return null;
  const name = filenameFromURL(candidate.url);
  const filename = safeFilename(/\.pdf$/i.test(name) ? name : `${candidate.label || "AWS-Academy-Student-Guide"}.pdf`);
  const captured=candidate.kind==="captured";
  return {url:candidate.url,filename,type:"PDF",variant:captured ? "Original PDF captured — ready to save" : "Original AWS Academy PDF",provider:"aws",captured};
}

function filesFromCandidate(candidate) {
  const aws = candidate && awsPDF(candidate);
  if (aws) return [aws];
  if (!isBlackboardURL(candidate?.url)) return [];
  const url = new URL(candidate.url);
  const viewerHost = /(^|\.)basic-doc-viewer\./i.test(url.hostname);
  const files = [];
  if (viewerHost) {
    // URLSearchParams performs exactly one outer decoding. Do not decode a
    // signed URL again: that would change escaped +, &, %, or / in its token.
    for (const [parameter, format] of [["originalUrl", "original"], ["pdfUrl", "pdf"]]) {
      const source = url.searchParams.get(parameter);
      if (source) {
        const file = candidateFile(source, candidate.label, format, true);
        if (file) files.push(file);
      }
    }
  } else {
    const file = candidateFile(candidate.url, candidate.label, "original", false);
    if (file) files.push(file);
  }
  return files;
}

function mergeCandidates(candidates) {
  const files = new Map();
  for (const candidate of candidates) {
    for (const file of filesFromCandidate(candidate)) {
      if (!files.has(file.url) || (file.captured && !files.get(file.url).captured)) files.set(file.url, file);
    }
  }
  return [...files.values()];
}

// Each function is self-contained because scripting.executeScript serializes it.
// Only the explicitly selected PDF is fetched, within its original viewer frame.
async function preparePdfTransfer(url, id, expectedOrigin) {
  const allowed = ["https://awsacademy.instructure.com","https://emergingtalent.contentcontroller.com","https://awsacademy.contentcontroller.com"];
  if (!allowed.includes(expectedOrigin) || location.origin !== expectedOrigin) return {ok:false,code:"FRAME_CHANGED"};
  try {
    const source = new URL(url);
    const host = source.hostname;
    const permitted = allowed.includes(source.origin) || host.endsWith(".cloudfront.net") || host.endsWith(".amazonaws.com");
    if (source.protocol !== "https:" || source.username || source.password || !permitted) return {ok:false,code:"UNSUPPORTED_SOURCE"};
  } catch { return {ok:false,code:"UNSUPPORTED_SOURCE"}; }
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 60000);
  try {
    const captured=globalThis.__courseFileSaverCaptured?.get(url);
    if(captured?.bytes) {
      const bytes=captured.bytes;
      const store=globalThis.__courseFileSaverTransfers||(globalThis.__courseFileSaverTransfers=new Map());
      if(store.has(id))clearTimeout(store.get(id).expiry);
      const expiry=setTimeout(()=>store.delete(id),600000);
      store.set(id,{bytes,expiry});
      return {ok:true,size:bytes.byteLength,chunks:Math.ceil(bytes.byteLength/(512*1024)),captured:true};
    }
    const response = await fetch(url,{credentials:"include",cache:"force-cache",signal:controller.signal});
    if (!response.ok) return {ok:false,code:`HTTP_${response.status}`};
    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength > 128 * 1024 * 1024) return {ok:false,code:"TOO_LARGE"};
    if (String.fromCharCode(...bytes.slice(0,5)) !== "%PDF-") return {ok:false,code:"NOT_PDF"};
    const tail = String.fromCharCode(...bytes.slice(-2048));
    if (!tail.includes("%%EOF")) return {ok:false,code:"INCOMPLETE_PDF"};
    if (response.status === 206) {
      const range = response.headers.get("content-range")?.match(/^bytes (\d+)-(\d+)\/(\d+)$/);
      if (!range || Number(range[1]) !== 0 || Number(range[2])+1 !== Number(range[3]) || bytes.byteLength !== Number(range[3])) return {ok:false,code:"INCOMPLETE_PDF"};
    }
    const store = globalThis.__courseFileSaverTransfers || (globalThis.__courseFileSaverTransfers = new Map());
    if (store.has(id)) clearTimeout(store.get(id).expiry);
    const expiry = setTimeout(() => store.delete(id), 600000);
    store.set(id,{bytes,expiry});
    const chunkSize = 512 * 1024;
    return {ok:true,size:bytes.byteLength,chunks:Math.ceil(bytes.byteLength/chunkSize)};
  } catch { return {ok:false,code:controller.signal.aborted ? "TIMEOUT" : "NO_CAPTURED_PDF"}; }
  finally { clearTimeout(timeout); }
}

function readPdfTransferChunk(id, index) {
  const entry = globalThis.__courseFileSaverTransfers?.get(id);
  if (!entry || !Number.isInteger(index) || index < 0) return {ok:false,code:"TRANSFER_EXPIRED"};
  const chunkSize = 512 * 1024;
  const start = index * chunkSize;
  if (start >= entry.bytes.length) return {ok:false,code:"INVALID_CHUNK"};
  const bytes = entry.bytes.subarray(start,Math.min(start+chunkSize,entry.bytes.length));
  let binary = "";
  for (let i=0;i<bytes.length;i+=8192) binary += String.fromCharCode(...bytes.subarray(i,i+8192));
  return {ok:true,data:btoa(binary)};
}

function clearPdfTransfer(id) {
  const store = globalThis.__courseFileSaverTransfers;
  const entry = store?.get(id);
  if (entry) {clearTimeout(entry.expiry);store.delete(id);}
}

function transferError(code) {
  if (/^HTTP_\d+$/.test(code)) return `The guide's file server returned ${code.slice(5)}. Reopen the Student Guide and try again.`;
  return {
    FRAME_CHANGED:"The guide page changed. Reopen it and refresh the extension's file list.",
    UNSUPPORTED_SOURCE:"This file address is not supported.",
    NOT_PDF:"The server returned a login or other non-PDF response. No file was saved. Reopen the guide and try again.",
    INCOMPLETE_PDF:"The response was only part of the PDF. No incomplete file was saved.",
    TOO_LARGE:"This PDF exceeds the current 128 MB transfer limit.",
    TIMEOUT:"The viewer's PDF request timed out. Reopen the guide and try again.",
    TRANSFER_EXPIRED:"The guide was closed, changed, or the transfer expired. Reopen it and try again.",
    NO_CAPTURED_PDF:"Reload the Student Guide page once, wait for its pages to appear, then reopen the extension. It needs to capture the original PDF response while the guide loads."
  }[code] || "The PDF transfer failed. Reopen the guide and try again.";
}

async function retrieveOriginalPdf(api, job, id, progress = () => {}) {
  const target = {tabId:job.tabId,frameIds:[job.file.sourceFrameId]};
  async function invoke(func,args) {
    let results;
    try {results = await api.scripting.executeScript({target,world:"ISOLATED",func,args});}
    catch {throw new Error(transferError("TRANSFER_EXPIRED"));}
    const result = results.find(r => r.frameId === job.file.sourceFrameId) || results[0];
    if (!result || result.error || !result.result) throw new Error(transferError("TRANSFER_EXPIRED"));
    return result.result;
  }
  try {
    progress("Copying the original PDF from your guide's viewer…");
    const metadata = await invoke(preparePdfTransfer,[job.file.url,id,job.file.sourceOrigin]);
    if (!metadata.ok) throw new Error(transferError(metadata.code));
    const parts = [];
    let received = 0;
    for(let index=0;index<metadata.chunks;index++) {
      const chunk = await invoke(readPdfTransferChunk,[id,index]);
      if (!chunk.ok) throw new Error(transferError(chunk.code));
      const binary = atob(chunk.data);
      const bytes = Uint8Array.from(binary,c=>c.charCodeAt(0));
      received += bytes.byteLength;
      parts.push(bytes);
      progress(`Copying original PDF: ${Math.round(received/metadata.size*100)}%`);
    }
    if (received !== metadata.size) throw new Error("The PDF transfer was incomplete. No file was saved.");
    return new Blob(parts,{type:"application/pdf"});
  } finally {
    try {await api.scripting.executeScript({target,world:"ISOLATED",func:clearPdfTransfer,args:[id]});} catch { /* Navigating the guide also destroys its isolated transfer buffer. */ }
  }
}


async function downloadCapturedPdf(api,job,objectURLs=URL) {
  if(!Number.isInteger(job?.tabId)||!Number.isInteger(job.file?.sourceFrameId)||
     job.file?.provider!=="aws"||!job.file.captured||
     !isAllowedDownloadURL(job.file.url)||!isAWSAcademyURL(job.file.sourceOrigin)) {
    throw new Error("Reopen the guide and refresh its file list.");
  }
  const pdf=await retrieveOriginalPdf(api,job,crypto.randomUUID());
  let url;
  const blobSupported=typeof objectURLs.createObjectURL==="function";
  if(blobSupported) {
    // Zen/Firefox rejects data: downloads. Its hidden background page owns this
    // blob, so closing the popup cannot revoke it. Avoid an idle file picker.
    url=objectURLs.createObjectURL(pdf);
  }else {
    // Chrome service workers do not implement createObjectURL.
    const bytes=new Uint8Array(await pdf.arrayBuffer());
    const parts=[];
    for(let start=0;start<bytes.length;start+=8192)parts.push(String.fromCharCode(...bytes.subarray(start,start+8192)));
    url="data:application/pdf;base64,"+btoa(parts.join(""));
  }
  try {
    let id;
    try {id=await api.downloads.download({url,filename:safeFilename(job.file.filename),saveAs:false,conflictAction:"uniquify"});}
    catch{throw new Error("The browser rejected the download. Reopen the extension and try again.");}
    await waitForSavedPdf(api,id);
    return id;
  }finally {if(blobSupported)objectURLs.revokeObjectURL(url);}
}

function waitForSavedPdf(api,id) {
  return new Promise((resolve,reject)=>{
    let finished=false;
    const cleanup=()=>{finished=true;clearInterval(poll);clearTimeout(timeout);api.downloads.onChanged.removeListener(changed);};
    const check=async()=>{
      if(finished)return;
      try {
        const [item]=await api.downloads.search({id});
        if(finished)return;
        if(item?.state==="complete"){cleanup();resolve();}
        else if(item?.state==="interrupted"){cleanup();reject(new Error("The browser interrupted the download. Check its downloads panel and try again."));}
      }catch{if(!finished){cleanup();reject(new Error("Could not verify the saved PDF. Check your browser's downloads panel."));}}
    };
    const changed=delta=>{if(delta.id===id)check();};
    const poll=setInterval(check,1000);
    const timeout=setTimeout(()=>{cleanup();reject(new Error("The download did not finish in time. Check your browser's downloads panel."));},180000);
    api.downloads.onChanged.addListener(changed);
    check();
  });
}


const api=globalThis.browser||globalThis.chrome;
api.runtime.onMessage.addListener((message,sender,respond)=>{
  if(message?.type!=="CFS_DOWNLOAD_PDF"||sender.id!==api.runtime.id||sender.url!==api.runtime.getURL("popup.html"))return;
  downloadCapturedPdf(api,{tabId:message.tabId,file:message.file})
    .then(downloadId=>respond({ok:true,downloadId}))
    .catch(error=>respond({ok:false,error:error instanceof Error?error.message:"The PDF could not be saved."}));
  // Keep the request alive even if the action popup closes during Save As.
  return true;
});

})();
