import test from "node:test";
import assert from "node:assert/strict";
import vm from "node:vm";
import {readFile} from "node:fs/promises";

const generated=await readFile(new URL("../background.js",import.meta.url),"utf8");
const inputs=["core.mjs","pdf-transfer.mjs","background-download.mjs","background.mjs"];
test("the shipped background bundle matches its source modules",async()=>{
  const sources=await Promise.all(inputs.map(file=>readFile(new URL("../"+file,import.meta.url),"utf8")));
  const code=sources.map(source=>source.replace(/^import .*;\n/gm,"").replace(/^export /gm,"")).join("\n");
  assert.equal(generated,'// Generated by node build-background.mjs. Edit the source modules.\n(()=>{\n'+code+'\n})();\n');
});
test("background registers synchronously and restricts requests to its own popup",async()=>{
  let listener;
  const api={runtime:{id:"extension-id",getURL(path){return "moz-extension://example/"+path;},onMessage:{addListener(fn){listener=fn;}}}};
  vm.runInNewContext(generated,{browser:api,URL});
  assert.equal(typeof listener,"function");
  assert.equal(listener({type:"CFS_DOWNLOAD_PDF"},{id:"other",url:api.runtime.getURL("popup.html")},()=>assert.fail("untrusted caller")),undefined);
  assert.equal(listener({type:"CFS_DOWNLOAD_PDF"},{id:api.runtime.id,url:api.runtime.getURL("other.html")},()=>assert.fail("wrong page")),undefined);
  let responded;
  assert.equal(listener({type:"CFS_DOWNLOAD_PDF"},{id:api.runtime.id,url:api.runtime.getURL("popup.html")},value=>{responded=value;}),true);
  await new Promise(resolve=>setTimeout(resolve,0));
  assert.equal(responded.ok,false);
  assert.match(responded.error,/Reopen the guide/);
});
